Updated readme file and started adding new flags to the script.

diff --git a/usr/bin/build4repo b/usr/bin/build4repo
--- a/usr/bin/build4repo
+++ b/usr/bin/build4repo
@@ -15,9 +15,10 @@ cd "$PWD"
 currentDir=${PWD##*/}
 thBuildAssets=".pkgbuild"
 pushRepo=0
+noConfirm=''
 
 ##  New section that accepts args -y and -n for yes and no
-while getopts ":y:n:" option; do
+while getopts ":yn:c:" option; do
     case $option in
     y)
         pushRepo=2
@@ -26,7 +27,13 @@ while getopts ":y:n:" option; do
     n)
         pushRepo=1
         ;;
-
+    c)
+       noConfirm='--noconfirm'
+        ;;
+    ?)
+        echo "Invalid option: -${OPTARG}."
+        exit 1
+        ;;
     esac
 done
 
@@ -76,7 +83,7 @@ else
     fi
 fi
 
-if !( makepkg -csrf --sign ); then
+if !( makepkg -csrf --sign $noConfirm ); then
     echo "This is not a PKGBUILD"
     not_my_dir
     something_wrong
